<?php
$nombre = $form->get('nombres');
$nombre->setAttribute('class', 'form-control');
$nombre->setAttribute('placeholder', 'Nombre');

$apellido = $form->get('apellidos');
$apellido->setAttribute('class', 'form-control');
$apellido->setAttribute('placeholder', 'Apellido');

$fecha_nacimiento = $form->get('fecha_nacimiento');
$fecha_nacimiento->setAttribute('class', 'form-control');
$fecha_nacimiento->setAttribute('placeholder', 'Fecha nacimiento');

$carrera_id = $form->get('carrera_id');
$carrera_id->setAttribute('class', 'form-control');
$carrera_id->setAttribute('placeholder', '0');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
 
$form->setAttribute('action', $this->url('alumnos', ['action' => 'create']));
$form->prepare();
 
echo $this->form()->openTag($form);
?>
 
<div class="form-group">
   <?= $this->formLabel($nombre) ?>
   <?= $this->formElement($nombre) ?>
   <?= $this->formElementErrors()->render($nombre, ['class' => 'help-block text-danger']) ?>
</div>

<div class="form-group">
   <?= $this->formLabel($apellido) ?>
   <?= $this->formElement($apellido) ?>
   <?= $this->formElementErrors()->render($apellido, ['class' => 'help-block text-danger']) ?>
</div>

<div class="form-group">
   <?= $this->formLabel($fecha_nacimiento) ?>
   <?= $this->formElement($fecha_nacimiento) ?>
   <?= $this->formElementErrors()->render($fecha_nacimiento, ['class' => 'help-block text-danger']) ?>
</div>

<div class="form-group">
   <?= $this->formLabel($carrera_id) ?>
   <?= $this->formElement($carrera_id) ?>
   <?= $this->formElementErrors()->render($carrera_id, ['class' => 'help-block text-danger']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('foto'));
echo $this->form()->closeTag();
?>