<?php
   $title = 'Editar alumno';
   $this->headTitle($title);
?>
<h4 class="d-flex justify-content-between align-items-center mb-3 mt-3">
   <span class="text-muted"><?=$title?></span>
</h4>

<?php
$nombres = $form->get('nombres');
$nombres->setAttribute('class', 'form-control');
$nombres->setAttribute('placeholder', 'Nombre');

$apellido = $form->get('apellidos');
$apellido->setAttribute('class', 'form-control');
$apellido->setAttribute('placeholder', 'Apellido');

$fecha_nacimiento = $form->get('fecha_nacimiento');
$fecha_nacimiento->setAttribute('class', 'form-control');
$fecha_nacimiento->setAttribute('placeholder', 'Fecha nacimiento');

$carrera_id = $form->get('carrera_id');
$carrera_id->setAttribute('class', 'form-control');
$carrera_id->setAttribute('placeholder', 'Carrera');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('alumnos', ['action' => 'edit', 'id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);
?>
   <div class="form-group">
       <?= $this->formLabel($nombres) ?>
       <?= $this->formElement($nombres) ?>
       <?= $this->formElementErrors()->render($nombres, ['class' => 'help-block text-danger']) ?>
   </div>

   <div class="form-group">
       <?= $this->formLabel($apellido) ?>
       <?= $this->formElement($apellido) ?>
       <?= $this->formElementErrors()->render($apellido, ['class' => 'help-block text-danger']) ?>
   </div>

   <div class="form-group">
       <?= $this->formLabel($fecha_nacimiento) ?>
       <?= $this->formElement($fecha_nacimiento) ?>
       <?= $this->formElementErrors()->render($fecha_nacimiento, ['class' => 'help-block text-danger']) ?>
   </div>

   <div class="form-group">
       <?= $this->formLabel($carrera_id) ?>
       <?= $this->formElement($carrera_id) ?>
       <?= $this->formElementErrors()->render($carrera_id, ['class' => 'help-block text-danger']) ?>
   </div>
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>