<?php
   $title = 'Editar alumno';
   $this->headTitle($title);
?>
<h4 class="d-flex justify-content-between align-items-center mb-3 mt-3">
   <span class="text-muted"><?=$title?></span>
</h4>

<?php
$alumno_id = $form->get('alumno_id');
$alumno_id->setAttribute('class', 'form-control');
$alumno_id->setAttribute('placeholder', 'Alumnos');

$semestre_id = $form->get('semestre_id');
$semestre_id->setAttribute('class', 'form-control');
$semestre_id->setAttribute('placeholder', 'Semestre');

$curso_id = $form->get('curso_id');
$curso_id->setAttribute('class', 'form-control');
$curso_id->setAttribute('placeholder', 'Curso');

$nota = $form->get('nota');
$nota->setAttribute('class', 'form-control');
$nota->setAttribute('placeholder', 'Nota');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('asignacionCursos', ['action' => 'edit', 'id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);
?>
   <div class="form-group">
       <?= $this->formLabel($alumno_id) ?>
       <?= $this->formElement($alumno_id) ?>
       <?= $this->formElementErrors()->render($alumno_id, ['class' => 'help-block text-danger']) ?>
   </div>

   <div class="form-group">
       <?= $this->formLabel($semestre_id) ?>
       <?= $this->formElement($semestre_id) ?>
       <?= $this->formElementErrors()->render($semestre_id, ['class' => 'help-block text-danger']) ?>
   </div>

   <div class="form-group">
       <?= $this->formLabel($curso_id) ?>
       <?= $this->formElement($curso_id) ?>
       <?= $this->formElementErrors()->render($curso_id, ['class' => 'help-block text-danger']) ?>
   </div>

   <div class="form-group">
       <?= $this->formLabel($nota) ?>
       <?= $this->formElement($nota) ?>
       <?= $this->formElementErrors()->render($nota, ['class' => 'help-block text-danger']) ?>
   </div>
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>